export const ZineListFull = [
  {
    id: 1,
    coverImage: '~../../assets/images/cover_vol_1.png',
    zineTitle: 'Volume 1',
    zineDescription:
      'First issue of the A2K Magazine, a collection of comics by different creators around the web. Please leave a comment if you would be interested in more issues in the future.',
    releaseDate: 'Aug 11, 2022',
    pdf_file: 'assets/zinespdf/v_1/a2kMagazine_v1i1_allPages.pdf',
    pages: [
      '~../../assets/zinespdf/v_1/a2kMagazine_v1i1_allPages_1.png',
      '~../../assets/zinespdf/v_1/a2kMagazine_v1i1_allPages_2.png',
      '~../../assets/zinespdf/v_1/a2kMagazine_v1i1_allPages_3.png',
      '~../../assets/zinespdf/v_1/a2kMagazine_v1i1_allPages_4.png',
      '~../../assets/zinespdf/v_1/a2kMagazine_v1i1_allPages_5.png',
      '~../../assets/zinespdf/v_1/a2kMagazine_v1i1_allPages_6.png',
      '~../../assets/zinespdf/v_1/a2kMagazine_v1i1_allPages_7.png',
      '~../../assets/zinespdf/v_1/a2kMagazine_v1i1_allPages_8.png',
      '~../../assets/zinespdf/v_1/a2kMagazine_v1i1_allPages_9.png',
      '~../../assets/zinespdf/v_1/a2kMagazine_v1i1_allPages_10.png',
      '~../../assets/zinespdf/v_1/a2kMagazine_v1i1_allPages_11.png',
      '~../../assets/zinespdf/v_1/a2kMagazine_v1i1_allPages_12.png',
      '~../../assets/zinespdf/v_1/a2kMagazine_v1i1_allPages_13.png',
      '~../../assets/zinespdf/v_1/a2kMagazine_v1i1_allPages_14.png',
      '~../../assets/zinespdf/v_1/a2kMagazine_v1i1_allPages_15.png',
      '~../../assets/zinespdf/v_1/a2kMagazine_v1i1_allPages_16.png',
      '~../../assets/zinespdf/v_1/a2kMagazine_v1i1_allPages_17.png',
      '~../../assets/zinespdf/v_1/a2kMagazine_v1i1_allPages_18.png',
      '~../../assets/zinespdf/v_1/a2kMagazine_v1i1_allPages_19.png',
      '~../../assets/zinespdf/v_1/a2kMagazine_v1i1_allPages_20.png',
      '~../../assets/zinespdf/v_1/a2kMagazine_v1i1_allPages_21.png',
      '~../../assets/zinespdf/v_1/a2kMagazine_v1i1_allPages_22.png',
      '~../../assets/zinespdf/v_1/a2kMagazine_v1i1_allPages_23.png',
      '~../../assets/zinespdf/v_1/a2kMagazine_v1i1_allPages_24.png',
      '~../../assets/zinespdf/v_1/a2kMagazine_v1i1_allPages_25.png',
      '~../../assets/zinespdf/v_1/a2kMagazine_v1i1_allPages_26.png',
    ],
  },
  {
    id: 2,
    coverImage: '~../../assets/images/cover_vol_2.png',
    zineTitle: 'Volume 2',
    zineDescription:
      'Second issue of the A2K Magazine, a collection of comics by different creators around the web.',
    releaseDate: 'Sep 13, 2022',
    pdf_file: 'assets/zinespdf/v_2/a2kMagazineissue2_pages.pdf',
    pages: [
      '~../../assets/zinespdf/v_2/a2kMagazineissue2_pages_1.png',
      '~../../assets/zinespdf/v_2/a2kMagazineissue2_pages_2.png',
      '~../../assets/zinespdf/v_2/a2kMagazineissue2_pages_3.png',
      '~../../assets/zinespdf/v_2/a2kMagazineissue2_pages_4.png',
      '~../../assets/zinespdf/v_2/a2kMagazineissue2_pages_5.png',
      '~../../assets/zinespdf/v_2/a2kMagazineissue2_pages_6.png',
      '~../../assets/zinespdf/v_2/a2kMagazineissue2_pages_7.png',
      '~../../assets/zinespdf/v_2/a2kMagazineissue2_pages_8.png',
      '~../../assets/zinespdf/v_2/a2kMagazineissue2_pages_9.png',
      '~../../assets/zinespdf/v_2/a2kMagazineissue2_pages_10.png',
      '~../../assets/zinespdf/v_2/a2kMagazineissue2_pages_11.png',
      '~../../assets/zinespdf/v_2/a2kMagazineissue2_pages_12.png',
      '~../../assets/zinespdf/v_2/a2kMagazineissue2_pages_13.png',
      '~../../assets/zinespdf/v_2/a2kMagazineissue2_pages_14.png',
      '~../../assets/zinespdf/v_2/a2kMagazineissue2_pages_15.png',
      '~../../assets/zinespdf/v_2/a2kMagazineissue2_pages_16.png',
      '~../../assets/zinespdf/v_2/a2kMagazineissue2_pages_17.png',
      '~../../assets/zinespdf/v_2/a2kMagazineissue2_pages_18.png',
      '~../../assets/zinespdf/v_2/a2kMagazineissue2_pages_19.png',
      '~../../assets/zinespdf/v_2/a2kMagazineissue2_pages_20.png',
      '~../../assets/zinespdf/v_2/a2kMagazineissue2_pages_21.png',
      '~../../assets/zinespdf/v_2/a2kMagazineissue2_pages_22.png',
      '~../../assets/zinespdf/v_2/a2kMagazineissue2_pages_23.png',
      '~../../assets/zinespdf/v_2/a2kMagazineissue2_pages_24.png',
      '~../../assets/zinespdf/v_2/a2kMagazineissue2_pages_25.png',
      '~../../assets/zinespdf/v_2/a2kMagazineissue2_pages_26.png',
    ],
  },
  {
    id: 3,
    coverImage: '~../../assets/images/cover_vol_3.png',
    zineTitle: 'Volume 3',
    zineDescription:
      'Third issue of the A2K Magazine, a collection of comics by different creators around the web.',
    releaseDate: 'Oct 18, 2022',
    pdf_file: 'assets/zinespdf/v_3/a2kcityMagazine3_pages.pdf',
    pages: [
      '~../../assets/zinespdf/v_3/a2kcityMagazine3_pages_1.png',
      '~../../assets/zinespdf/v_3/a2kcityMagazine3_pages_2.png',
      '~../../assets/zinespdf/v_3/a2kcityMagazine3_pages_3.png',
      '~../../assets/zinespdf/v_3/a2kcityMagazine3_pages_4.png',
      '~../../assets/zinespdf/v_3/a2kcityMagazine3_pages_5.png',
      '~../../assets/zinespdf/v_3/a2kcityMagazine3_pages_6.png',
      '~../../assets/zinespdf/v_3/a2kcityMagazine3_pages_7.png',
      '~../../assets/zinespdf/v_3/a2kcityMagazine3_pages_8.png',
      '~../../assets/zinespdf/v_3/a2kcityMagazine3_pages_9.png',
      '~../../assets/zinespdf/v_3/a2kcityMagazine3_pages_10.png',
      '~../../assets/zinespdf/v_3/a2kcityMagazine3_pages_11.png',
      '~../../assets/zinespdf/v_3/a2kcityMagazine3_pages_12.png',
      '~../../assets/zinespdf/v_3/a2kcityMagazine3_pages_13.png',
      '~../../assets/zinespdf/v_3/a2kcityMagazine3_pages_14.png',
      '~../../assets/zinespdf/v_3/a2kcityMagazine3_pages_15.png',
      '~../../assets/zinespdf/v_3/a2kcityMagazine3_pages_16.png',
      '~../../assets/zinespdf/v_3/a2kcityMagazine3_pages_17.png',
      '~../../assets/zinespdf/v_3/a2kcityMagazine3_pages_18.png',
      '~../../assets/zinespdf/v_3/a2kcityMagazine3_pages_19.png',
      '~../../assets/zinespdf/v_3/a2kcityMagazine3_pages_20.png',
      '~../../assets/zinespdf/v_3/a2kcityMagazine3_pages_21.png',
      '~../../assets/zinespdf/v_3/a2kcityMagazine3_pages_22.png',
      '~../../assets/zinespdf/v_3/a2kcityMagazine3_pages_23.png',
      '~../../assets/zinespdf/v_3/a2kcityMagazine3_pages_24.png',
      '~../../assets/zinespdf/v_3/a2kcityMagazine3_pages_25.png',
      '~../../assets/zinespdf/v_3/a2kcityMagazine3_pages_26.png',
      '~../../assets/zinespdf/v_3/a2kcityMagazine3_pages_27.png',
      '~../../assets/zinespdf/v_3/a2kcityMagazine3_pages_28.png',
      '~../../assets/zinespdf/v_3/a2kcityMagazine3_pages_29.png',
      '~../../assets/zinespdf/v_3/a2kcityMagazine3_pages_30.png',
      '~../../assets/zinespdf/v_3/a2kcityMagazine3_pages_31.png',
      '~../../assets/zinespdf/v_3/a2kcityMagazine3_pages_32.png',
    ],
  },
  {
    id: 4,
    coverImage: '~../../assets/images/cover_vol_4.png',
    zineTitle: 'Volume 4',
    zineDescription:
      'Forth issue of the A2K Magazine, a collection of comics by different creators around the web.',
    releaseDate: 'Feb 16, 2023',
    pdf_file: 'assets/zinespdf/v_4/a2kcityzine4_allPages.pdf',
    pages: [
      '~../../assets/zinespdf/v_4/a2kcityzine4_allPages_1.png',
      '~../../assets/zinespdf/v_4/a2kcityzine4_allPages_2.png',
      '~../../assets/zinespdf/v_4/a2kcityzine4_allPages_3.png',
      '~../../assets/zinespdf/v_4/a2kcityzine4_allPages_4.png',
      '~../../assets/zinespdf/v_4/a2kcityzine4_allPages_5.png',
      '~../../assets/zinespdf/v_4/a2kcityzine4_allPages_6.png',
      '~../../assets/zinespdf/v_4/a2kcityzine4_allPages_7.png',
      '~../../assets/zinespdf/v_4/a2kcityzine4_allPages_8.png',
      '~../../assets/zinespdf/v_4/a2kcityzine4_allPages_9.png',
      '~../../assets/zinespdf/v_4/a2kcityzine4_allPages_10.png',
      '~../../assets/zinespdf/v_4/a2kcityzine4_allPages_11.png',
      '~../../assets/zinespdf/v_4/a2kcityzine4_allPages_12.png',
      '~../../assets/zinespdf/v_4/a2kcityzine4_allPages_13.png',
      '~../../assets/zinespdf/v_4/a2kcityzine4_allPages_14.png',
      '~../../assets/zinespdf/v_4/a2kcityzine4_allPages_15.png',
      '~../../assets/zinespdf/v_4/a2kcityzine4_allPages_16.png',
      '~../../assets/zinespdf/v_4/a2kcityzine4_allPages_17.png',
      '~../../assets/zinespdf/v_4/a2kcityzine4_allPages_18.png',
      '~../../assets/zinespdf/v_4/a2kcityzine4_allPages_19.png',
      '~../../assets/zinespdf/v_4/a2kcityzine4_allPages_20.png',
      '~../../assets/zinespdf/v_4/a2kcityzine4_allPages_21.png',
      '~../../assets/zinespdf/v_4/a2kcityzine4_allPages_22.png',
      '~../../assets/zinespdf/v_4/a2kcityzine4_allPages_23.png',
      '~../../assets/zinespdf/v_4/a2kcityzine4_allPages_24.png',
    ],
  },
  {
    id: 5,
    coverImage: '~../../assets/images/cover_vol_5.png',
    zineTitle: 'Volume 5',
    zineDescription:
      'Fifth issue of the A2K Magazine, a collection of comics by different creators around the web.',
    releaseDate: 'Apr 17, 2023',
    pdf_file: 'assets/zinespdf/v_5/a2kcityMagazine5_allPages.pdf',
    pages: [
      '~../../assets/zinespdf/v_5/a2kcityMagazine5_allPages_1.png',
      '~../../assets/zinespdf/v_5/a2kcityMagazine5_allPages_2.png',
      '~../../assets/zinespdf/v_5/a2kcityMagazine5_allPages_3.png',
      '~../../assets/zinespdf/v_5/a2kcityMagazine5_allPages_4.png',
      '~../../assets/zinespdf/v_5/a2kcityMagazine5_allPages_5.png',
      '~../../assets/zinespdf/v_5/a2kcityMagazine5_allPages_6.png',
      '~../../assets/zinespdf/v_5/a2kcityMagazine5_allPages_7.png',
      '~../../assets/zinespdf/v_5/a2kcityMagazine5_allPages_8.png',
      '~../../assets/zinespdf/v_5/a2kcityMagazine5_allPages_9.png',
      '~../../assets/zinespdf/v_5/a2kcityMagazine5_allPages_10.png',
      '~../../assets/zinespdf/v_5/a2kcityMagazine5_allPages_11.png',
      '~../../assets/zinespdf/v_5/a2kcityMagazine5_allPages_12.png',
      '~../../assets/zinespdf/v_5/a2kcityMagazine5_allPages_13.png',
      '~../../assets/zinespdf/v_5/a2kcityMagazine5_allPages_14.png',
      '~../../assets/zinespdf/v_5/a2kcityMagazine5_allPages_15.png',
      '~../../assets/zinespdf/v_5/a2kcityMagazine5_allPages_16.png',
      '~../../assets/zinespdf/v_5/a2kcityMagazine5_allPages_17.png',
      '~../../assets/zinespdf/v_5/a2kcityMagazine5_allPages_18.png',
      '~../../assets/zinespdf/v_5/a2kcityMagazine5_allPages_19.png',
      '~../../assets/zinespdf/v_5/a2kcityMagazine5_allPages_20.png',
      '~../../assets/zinespdf/v_5/a2kcityMagazine5_allPages_21.png',
      '~../../assets/zinespdf/v_5/a2kcityMagazine5_allPages_22.png',
      '~../../assets/zinespdf/v_5/a2kcityMagazine5_allPages_23.png',
      '~../../assets/zinespdf/v_5/a2kcityMagazine5_allPages_24.png',

    ],
  },
  {
    id: 6,
    coverImage: '~../../assets/images/cover_vol_6.png',
    zineTitle: 'Volume 6',
    zineDescription:
      'Sixth issue of the A2K Magazine, a collection of comics by different creators around the web. Please leave a comment if you would be interested in more issues in the future.',
    releaseDate: 'Jun 18, 2023',
    pdf_file: 'assets/zinespdf/v_6/a2kcityMagazine6_pages.pdf',
    pages: [
      '~../../assets/zinespdf/v_6/a2kcityMagazine6_pages_1.png',
      '~../../assets/zinespdf/v_6/a2kcityMagazine6_pages_2.png',
      '~../../assets/zinespdf/v_6/a2kcityMagazine6_pages_3.png',
      '~../../assets/zinespdf/v_6/a2kcityMagazine6_pages_4.png',
      '~../../assets/zinespdf/v_6/a2kcityMagazine6_pages_5.png',
      '~../../assets/zinespdf/v_6/a2kcityMagazine6_pages_6.png',
      '~../../assets/zinespdf/v_6/a2kcityMagazine6_pages_7.png',
      '~../../assets/zinespdf/v_6/a2kcityMagazine6_pages_8.png',
      '~../../assets/zinespdf/v_6/a2kcityMagazine6_pages_9.png',
      '~../../assets/zinespdf/v_6/a2kcityMagazine6_pages_10.png',
      '~../../assets/zinespdf/v_6/a2kcityMagazine6_pages_11.png',
      '~../../assets/zinespdf/v_6/a2kcityMagazine6_pages_12.png',
      '~../../assets/zinespdf/v_6/a2kcityMagazine6_pages_13.png',
      '~../../assets/zinespdf/v_6/a2kcityMagazine6_pages_14.png',
      '~../../assets/zinespdf/v_6/a2kcityMagazine6_pages_15.png',
      '~../../assets/zinespdf/v_6/a2kcityMagazine6_pages_16.png',
      '~../../assets/zinespdf/v_6/a2kcityMagazine6_pages_17.png',
      '~../../assets/zinespdf/v_6/a2kcityMagazine6_pages_18.png',
    ],
  },
  {
    id: 7,
    coverImage: '~../../assets/images/cover_vol_7.png',
    zineTitle: 'Volume 7',
    zineDescription:
      'Seventh issue of the A2K Magazine, a collection of comics by different creators around the web. Please leave a comment if you would be interested in more issues in the future.',
    releaseDate: 'Aug 17, 2023',
    pdf_file: 'assets/zinespdf/v_7/a2kcityMagazine7_pages.pdf',
    pages: [
      '~../../assets/zinespdf/v_7/a2kcityMagazine7_pages_1.png',
      '~../../assets/zinespdf/v_7/a2kcityMagazine7_pages_2.png',
      '~../../assets/zinespdf/v_7/a2kcityMagazine7_pages_3.png',
      '~../../assets/zinespdf/v_7/a2kcityMagazine7_pages_4.png',
      '~../../assets/zinespdf/v_7/a2kcityMagazine7_pages_5.png',
      '~../../assets/zinespdf/v_7/a2kcityMagazine7_pages_6.png',
      '~../../assets/zinespdf/v_7/a2kcityMagazine7_pages_7.png',
      '~../../assets/zinespdf/v_7/a2kcityMagazine7_pages_8.png',
      '~../../assets/zinespdf/v_7/a2kcityMagazine7_pages_9.png',
      '~../../assets/zinespdf/v_7/a2kcityMagazine7_pages_10.png',
      '~../../assets/zinespdf/v_7/a2kcityMagazine7_pages_11.png',
      '~../../assets/zinespdf/v_7/a2kcityMagazine7_pages_12.png',
      '~../../assets/zinespdf/v_7/a2kcityMagazine7_pages_13.png',
      '~../../assets/zinespdf/v_7/a2kcityMagazine7_pages_14.png',
      '~../../assets/zinespdf/v_7/a2kcityMagazine7_pages_15.png',
      '~../../assets/zinespdf/v_7/a2kcityMagazine7_pages_16.png',
      '~../../assets/zinespdf/v_7/a2kcityMagazine7_pages_17.png',
      '~../../assets/zinespdf/v_7/a2kcityMagazine7_pages_18.png',
      '~../../assets/zinespdf/v_7/a2kcityMagazine7_pages_19.png',
      '~../../assets/zinespdf/v_7/a2kcityMagazine7_pages_20.png',
      '~../../assets/zinespdf/v_7/a2kcityMagazine7_pages_21.png',
      '~../../assets/zinespdf/v_7/a2kcityMagazine7_pages_22.png',
      '~../../assets/zinespdf/v_7/a2kcityMagazine7_pages_23.png',
      '~../../assets/zinespdf/v_7/a2kcityMagazine7_pages_24.png',
      '~../../assets/zinespdf/v_7/a2kcityMagazine7_pages_25.png',
    ],
  },
  {
    id: 8,
    coverImage: '~../../assets/images/cover_vol_8.png',
    zineTitle: 'Volume 8',
    zineDescription:
      'Eight issue of the A2K Magazine, a collection of comics by different creators around the web. Please leave a comment if you would be interested in more issues in the future.',
    releaseDate: 'Oct 20, 2023',
    pdf_file: 'assets/zinespdf/v_8/a2kcityMagazine8_pages.pdf',
    pages: [
      '~../../assets/zinespdf/v_8/a2kcityMagazine8_pages_1.png',
      '~../../assets/zinespdf/v_8/a2kcityMagazine8_pages_2.png',
      '~../../assets/zinespdf/v_8/a2kcityMagazine8_pages_3.png',
      '~../../assets/zinespdf/v_8/a2kcityMagazine8_pages_4.png',
      '~../../assets/zinespdf/v_8/a2kcityMagazine8_pages_5.png',
      '~../../assets/zinespdf/v_8/a2kcityMagazine8_pages_6.png',
      '~../../assets/zinespdf/v_8/a2kcityMagazine8_pages_7.png',
      '~../../assets/zinespdf/v_8/a2kcityMagazine8_pages_8.png',
      '~../../assets/zinespdf/v_8/a2kcityMagazine8_pages_9.png',
      '~../../assets/zinespdf/v_8/a2kcityMagazine8_pages_10.png',
      '~../../assets/zinespdf/v_8/a2kcityMagazine8_pages_11.png',
      '~../../assets/zinespdf/v_8/a2kcityMagazine8_pages_12.png',
      '~../../assets/zinespdf/v_8/a2kcityMagazine8_pages_13.png',
      '~../../assets/zinespdf/v_8/a2kcityMagazine8_pages_14.png',
    ],
  },
  {
    id: 9,
    coverImage: '~../../assets/images/cover_vol_9.png',
    zineTitle: 'Volume 9',
    zineDescription:
      'Ninth issue of the A2K Magazine, a collection of comics by different creators around the web. Please leave a comment if you would be interested in more issues in the future.',
    releaseDate: 'Dec 19, 2023',
    pdf_file: 'assets/zinespdf/v_9/a2kcityMagazine9_pages.pdf',
    pages: [
      '~../../assets/zinespdf/v_9/a2kcityMagazine9_pages_1.png',
      '~../../assets/zinespdf/v_9/a2kcityMagazine9_pages_2.png',
      '~../../assets/zinespdf/v_9/a2kcityMagazine9_pages_3.png',
      '~../../assets/zinespdf/v_9/a2kcityMagazine9_pages_4.png',
      '~../../assets/zinespdf/v_9/a2kcityMagazine9_pages_5.png',
      '~../../assets/zinespdf/v_9/a2kcityMagazine9_pages_6.png',
      '~../../assets/zinespdf/v_9/a2kcityMagazine9_pages_7.png',
      '~../../assets/zinespdf/v_9/a2kcityMagazine9_pages_8.png',
      '~../../assets/zinespdf/v_9/a2kcityMagazine9_pages_9.png',
      '~../../assets/zinespdf/v_9/a2kcityMagazine9_pages_10.png',
      '~../../assets/zinespdf/v_9/a2kcityMagazine9_pages_11.png',
      '~../../assets/zinespdf/v_9/a2kcityMagazine9_pages_12.png',
      '~../../assets/zinespdf/v_9/a2kcityMagazine9_pages_13.png',
      '~../../assets/zinespdf/v_9/a2kcityMagazine9_pages_14.png',
      '~../../assets/zinespdf/v_9/a2kcityMagazine9_pages_15.png',
      '~../../assets/zinespdf/v_9/a2kcityMagazine9_pages_16.png',
      '~../../assets/zinespdf/v_9/a2kcityMagazine9_pages_17.png',
      '~../../assets/zinespdf/v_9/a2kcityMagazine9_pages_18.png',
      '~../../assets/zinespdf/v_9/a2kcityMagazine9_pages_19.png',
      '~../../assets/zinespdf/v_9/a2kcityMagazine9_pages_20.png',
      '~../../assets/zinespdf/v_9/a2kcityMagazine9_pages_21.png',
      '~../../assets/zinespdf/v_9/a2kcityMagazine9_pages_22.png',
      '~../../assets/zinespdf/v_9/a2kcityMagazine9_pages_23.png',
      '~../../assets/zinespdf/v_9/a2kcityMagazine9_pages_24.png',
      '~../../assets/zinespdf/v_9/a2kcityMagazine9_pages_25.png',
      '~../../assets/zinespdf/v_9/a2kcityMagazine9_pages_26.png',

    ],
  },
  {
    id: 10,
    coverImage: '~../../assets/images/cover_vol_10.png',
    zineTitle: 'Summer edition',
    zineDescription:
      'Tenth issue of the A2K Magazine, a collection of comics by different creators around the web. Please leave a comment if you would be interested in more issues in the future.',
    releaseDate: 'Jun 23, 2024',
    pdf_file: 'assets/zinespdf/v_10/A2K Summer 2024 Edition_.pdf',
    pages: [
      '~../../assets/zinespdf/v_10/A2K Summer 2024 Edition__1.png',
      '~../../assets/zinespdf/v_10/A2K Summer 2024 Edition__2.png',
      '~../../assets/zinespdf/v_10/A2K Summer 2024 Edition__3.png',
      '~../../assets/zinespdf/v_10/A2K Summer 2024 Edition__4.png',
      '~../../assets/zinespdf/v_10/A2K Summer 2024 Edition__5.png',
      '~../../assets/zinespdf/v_10/A2K Summer 2024 Edition__6.png',
      '~../../assets/zinespdf/v_10/A2K Summer 2024 Edition__7.png',
      '~../../assets/zinespdf/v_10/A2K Summer 2024 Edition__8.png',
      '~../../assets/zinespdf/v_10/A2K Summer 2024 Edition__9.png',
      '~../../assets/zinespdf/v_10/A2K Summer 2024 Edition__10.png',
      '~../../assets/zinespdf/v_10/A2K Summer 2024 Edition__11.png',
      '~../../assets/zinespdf/v_10/A2K Summer 2024 Edition__12.png',

    ],
  },
];
